INSERT INTO PRODUCT(ID_PRODUCT, PRODUCT_NAME, EXPIRATION_DATE,VERSION, REGISTER) VALUES(1,'CALÇA COURO',CURRENT_DATE, 1,CURRENT_DATE);
INSERT INTO PRODUCT(ID_PRODUCT, PRODUCT_NAME, EXPIRATION_DATE,VERSION, REGISTER) VALUES(2,'CALÇA JEANS',CURRENT_DATE, 1,CURRENT_DATE);
INSERT INTO PRODUCT(ID_PRODUCT, PRODUCT_NAME, EXPIRATION_DATE,VERSION, REGISTER) VALUES(3,'JAQUETA COURO',CURRENT_DATE, 1,CURRENT_DATE);
INSERT INTO PRODUCT_PRICE(ID_PRODUCT_PRICE, ID_PRODUCT, PRICE_VALUE, VERSION, REGISTER) VALUES(1, 1, 19.99, 1, CURRENT_DATE);
INSERT INTO PRODUCT_PRICE(ID_PRODUCT_PRICE, ID_PRODUCT, PRICE_VALUE, VERSION, REGISTER) VALUES(2, 2, 19.99, 1, CURRENT_DATE);